spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://localhost:3306/triple_mileage_db?rewriteBatchedStatements=true
  jpa:
    database: mysql
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true

decorator:
  datasource:
    p6spy:
      enable-logging: false

logging:
  level:
    root: error
    com.triple.mileageservice: info
